import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import AOSWrapper from "../../components/AOSWrapper"; // adjust path if needed
import Script from "next/script";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Billion Dollar FX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="8lTSuR5UYvf6hPgYpADzJxRnZCQ2eWRFJpSJ4KAcNC4"
        />
        <link rel="icon" href="/favicon.ico" />
        <style>{`
          body > .skiptranslate {
            display: none;
          }
          .goog-te-banner-frame.skiptranslate {
            display: none !important;
          }
          body {
            top: 0px !important;
          }
          @media print {
            #google_translate_element {
              display: none;
            }
          }
        `}</style>
        {/* Meta Pixel Code  */}
        <script>
          {`
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window, document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '2525742971143286');
    fbq('track', 'PageView');
  `}
        </script>

        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=2525742971143286&ev=PageView&noscript=1"
          />
        </noscript>
        {/* End Meta Pixel Code --> */}
      </head>
      <body className={montserrat.className}>
        <AOSWrapper>{children}</AOSWrapper>
      </body>
    </html>
  );
}
